// File: utils/__tests__/onboardingContext.validation.test.ts
import { readFileSync } from 'fs';
import { join } from 'path';

describe('Onboarding context collection', () => {
  const content = readFileSync(
    join(__dirname, '../../app/(onboarding)/screens/GetStartedScreen.tsx'), 'utf8');
  const orchestrator = readFileSync(
    join(__dirname, '../../app/(onboarding)/index.tsx'), 'utf8');

  test('GetStartedScreen has a patient name input', () => {
    expect(content).toMatch(/TextInput|patient.*name/i);
  });

  // The bucket-grid selection UI was retired in v6.7. The default care plan
  // is now generated by onboardingToPlan.ts at the orchestrator level from
  // careMode + name alone — no per-screen bucket toggling.

  test('GetStartedScreen saves patient name on completion', () => {
    expect(content).toMatch(/patient_name|PATIENT_NAME|patientRegistry|patientNameWriter/i);
  });

  test('orchestrator generates the default care plan via generateCarePlanFromOnboarding', () => {
    expect(orchestrator).toMatch(/generateCarePlanFromOnboarding\(/);
    expect(orchestrator).toMatch(/saveCarePlanConfig\(/);
  });

  test('sample data is NOT default', () => {
    expect(content).not.toMatch(/seedSampleData.*true.*default/i);
  });
});
