// ============================================================================
// HANDOFF REPORT BUILDER
// Formats today's care data into a structured text report for shift changes
// ============================================================================

import { buildTodaySummary, TodaySummary } from './careSummaryBuilder';
import { getTodayDateString } from '../services/carePlanGenerator';
import { logError } from './devLog';

// ============================================================================
// BUILDER
// ============================================================================

export async function buildHandoffReport(): Promise<string> {
  try {
    const summary = await buildTodaySummary();
    const today = getTodayDateString();
    const now = new Date();
    const timeStr = now.toLocaleTimeString('en-US', { hour: 'numeric', minute: '2-digit' });
    const dateStr = now.toLocaleDateString('en-US', { weekday: 'long', month: 'long', day: 'numeric', year: 'numeric' });

    const lines: string[] = [];

    // Header
    lines.push('CAREGIVER HANDOFF REPORT');
    lines.push(`${dateStr} at ${timeStr}`);
    lines.push('---');

    // Medication Adherence
    lines.push('');
    lines.push('MEDICATIONS');
    if (summary.medsAdherence.total > 0) {
      const { taken, total } = summary.medsAdherence;
      const pct = Math.round((taken / total) * 100);
      lines.push(`  ${taken}/${total} logged (${pct}%)`);
      if (taken < total) {
        const remaining = total - taken;
        lines.push(`  ${remaining} still pending`);
      }
    } else {
      lines.push('  No medications scheduled');
    }

    // Wellness Snapshot
    lines.push('');
    lines.push('WELLNESS');
    if (summary.moodArc) {
      lines.push(`  Mood: ${summary.moodArc}`);
    }
    if (summary.orientation) {
      lines.push(`  Orientation: ${summary.orientation}`);
    }
    if (summary.painLevel) {
      lines.push(`  Pain: ${summary.painLevel}`);
    }
    if (summary.alertness) {
      lines.push(`  Alertness: ${summary.alertness}`);
    }
    if (summary.appetite) {
      lines.push(`  Appetite: ${summary.appetite}`);
    }
    if (!summary.moodArc && !summary.orientation && !summary.painLevel && !summary.alertness && !summary.appetite) {
      lines.push('  No wellness data logged');
    }

    // Vitals
    if (summary.vitalsReading) {
      lines.push('');
      lines.push('VITALS');
      lines.push(`  ${summary.vitalsReading}`);
    }

    // Meals
    if (summary.mealsStatus) {
      lines.push('');
      lines.push('MEALS');
      lines.push(`  ${summary.mealsStatus.logged}/${summary.mealsStatus.total} logged`);
      if (summary.mealsStatus.overdueNames.length > 0) {
        lines.push(`  Overdue: ${summary.mealsStatus.overdueNames.join(', ')}`);
      }
    }

    // Overdue Items
    if (summary.overdueItems.length > 0) {
      lines.push('');
      lines.push('PENDING ITEMS');
      for (const item of summary.overdueItems) {
        lines.push(`  - ${item}`);
      }
    }

    // Flagged Items
    if (summary.flaggedItems.length > 0) {
      lines.push('');
      lines.push('ATTENTION');
      for (const flag of summary.flaggedItems) {
        lines.push(`  ! ${flag}`);
      }
    }

    // Next Appointment
    if (summary.nextAppointment) {
      lines.push('');
      lines.push('NEXT APPOINTMENT');
      const apptDate = new Date(summary.nextAppointment.date);
      const apptStr = apptDate.toLocaleDateString('en-US', { weekday: 'short', month: 'short', day: 'numeric' });
      lines.push(`  ${summary.nextAppointment.provider} (${summary.nextAppointment.specialty})`);
      lines.push(`  ${apptStr}`);
    }

    // Footer
    lines.push('');
    lines.push('---');
    lines.push('Generated by EmberMate');

    return lines.join('\n');
  } catch (error) {
    logError('buildHandoffReport', error);
    throw error;
  }
}
